export const FETCH_PRODUCTS ='FETCH_PRODUCTS';
export const FILTER_PRODUCTS_BY_GENRE ='FILTER_PRODUCTS_BY_GENRE';
export const FILTER_PRODUCTS_BY_PRICE ='FILTER_PRODUCTS_BY_PRICE';
export const FILTER_PRODUCTS_BY_SIZE ='FILTER_PRODUCTS_BY_SIZE';
export const FILTER_PRODUCTS_BY_BRAND ='FILTER_PRODUCTS_BY_BRAND';
export const FILTER_PRODUCTS_BY_TYPE ='FILTER_PRODUCTS_BY_TYPE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';